### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by sevisalas** [emastra/google-shopping-scraper-puppeteer#33]
Hi
I am getting empty file (no results) using tasks. created with your actor, too many errors:

2022-03-31T14:45:11.692Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"http://www.google.fr/search?q=Calendriers%20muraux&tbm=shop&tbs=vw:l","retryCount":15,"id":"6JOqye9xVAJOiWC"}
2022-03-31T14:45:11.694Z   Error: Page didn't load properly, retrying...
2022-03-31T14:45:11.696Z       at Object.exports.SEARCH_PAGE (/home/myuser/src/routes.js:17:15)
2022-03-31T14:45:11.697Z       at runMicrotasks (<anonymous>)
2022-03-31T14:45:11.701Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-31T14:45:11.704Z       at async wrap (/home/myuser/node_modules/@apify/timeout/index.js:73:27)
2022-03-31T14:45:12.409Z WARN  Request http://www.google.fr/search?q=Banner&tbm=shop&tbs=vw:l failed too many times
2022-03-31T14:45:14.995Z INFO  Processing: http://www.google.fr/search?q=Affiches&tbm=shop&tbs=vw:l
2022-03-31T14:45:15.000Z INFO  Number of page: 1
2022-03-31T14:45:15.004Z ERROR PuppeteerCrawler: handleRequestFunction failed, reclaiming failed request back to the list or queue {"url":"http://www.google.fr/search?q=Affiches&tbm=shop&tbs=vw:l","retryCount":15,"id":"lGc8cEYhigGw2Di"}
2022-03-31T14:45:15.006Z   Error: Page didn't load properly, retrying...
2022-03-31T14:45:15.008Z       at Object.exports.SEARCH_PAGE (/home/myuser/src/routes.js:34:15)
2022-03-31T14:45:15.010Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-03-31T14:45:15.012Z       at async wrap (/home/myuser/node_modules/@apify/timeout/index.js:73:27)
2022-03-31T14:45:22.075Z INFO  Processing: http://www.google.fr/search?q=Calendriers%20muraux&tbm=shop&tbs=vw:l
2022-03-31T14:45:22.078Z INFO  Number of page: 1
2022-03-31T14:45:22.115Z WARN  Request http://www.google.fr/search?q=Calendriers%20muraux&tbm=shop&tbs=vw:l failed too many times
2022-03-31T14:45:24.074Z INFO  Processing: http://www.google.fr/search?q=Affiches&tbm=shop&tbs=vw:l
2022-03-31T14:45:24.077Z INFO  Number of page: 1
2022-03-31T14:45:24.106Z WARN  Request http://www.google.fr/search?q=Affiches&tbm=shop&tbs=vw:l failed too many times
2022-03-31T14:45:24.221Z INFO  PuppeteerCrawler: All the requests from request list and/or request queue have been processed, the crawler will shut down.
2022-03-31T14:45:24.513Z INFO  PuppeteerCrawler: Final request statistics: {"requestsFinished":0,"requestsFailed":9,"retryHistogram":[null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,9],"requestAvgFailedDurationMillis":12442,"requestAvgFinishedDurationMillis":null,"requestsFinishedPerMinute":0,"requestsFailedPerMinute":1,"requestTotalDurationMillis":111982,"requestsTotal":9,"crawlerRuntimeMillis":319574}
2022-03-31T14:45:24.516Z INFO  Crawler Finished.

Regards

**Comment by sevisalas** [comment]
sorry, exceed limits apify account, please close the issue
